[package]
name = "crash"
version = "0.1.0"
authors = ["McLutzifer <lukasschumi@gmx.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
